import fs from 'node:fs';
import path from 'node:path';
import readline from 'node:readline/promises';
import { crypto } from 'node:crypto';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

async function setup() {
  console.log('🚀 AGIAAS Setup - Environment Configuration');
  console.log('------------------------------------------');

  const envPath = path.resolve(process.cwd(), '.env');

  let envContent = '';
  if (fs.existsSync(envPath)) {
    console.log('ℹ️  .env file already exists. Skipping auto-generation.');
    process.exit(0);
  }

  // Security Keys Setup
  let dbKey;
  let authSecret;
  const autoGen = await rl.question('🚀 Auto-generate security keys (DB_ENCRYPTION_KEY, BETTER_AUTH_SECRET)? (Y/n): ');
  
  if (autoGen.toLowerCase() === 'n') {
    dbKey = await rl.question('Enter DB_ENCRYPTION_KEY (32 chars): ');
    authSecret = await rl.question('Enter BETTER_AUTH_SECRET: ');
  } else {
    dbKey = crypto.randomBytes(24).toString('base64');
    authSecret = crypto.randomBytes(32).toString('hex');
    console.log('✅ Security keys generated.');
  }

  console.log('\n📝 Let\'s collect the required API keys:');
  
  const nousKey = await rl.question('Enter your NOUS_API_KEY (optional, press enter to skip): ');
  const orKey = await rl.question('Enter your OPENROUTER_API_KEY (optional, press enter to skip): ');
  
  envContent = `
# Generated by AGIAAS Setup
DB_ENCRYPTION_KEY=${dbKey}
BETTER_AUTH_SECRET=${authSecret}

# API Keys
${nousKey ? `NOUS_API_KEY=${nousKey}` : '# NOUS_API_KEY='}
${orKey ? `OPENROUTER_API_KEY=${orKey}` : '# OPENROUTER_API_KEY='}

# Port Configuration
WEBHOOK_PORT=8678
PORT=3678
HERMES_AGENT_URL=http://hermes-agent:8678
`.trim();

  fs.writeFileSync(envPath, envContent);
  console.log('\n✅ .env file created successfully!');
  console.log('➡  You can now run: docker-compose up --build');
  
  rl.close();
}

setup().catch(console.error);
