# Auto-generated by Hermes AI Agent
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from playwright.sync_api import sync_playwright
import os

app = FastAPI()

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Health endpoint
@app.get("/health")
def health():
    return {"status": "ok"}

def scrape_data():
    data = []
    
    with sync_playwright() as p:
        browser = p.chromium.launch(args=["--no-sandbox", "--disable-dev-shm-usage"])
        context = browser.new_context(ignore_https_errors=True)
        page = context.new_page()
        
        # Navigate and wait for full load including JS
        page.goto("https://www.dr.com.tr/", wait_until="load", timeout=60000)
        
        # Scroll to trigger lazy loading
        for _ in range(3):
            page.evaluate("window.scrollTo(0, document.body ? document.body.scrollHeight : 0)")
            page.wait_for_timeout(1000)
        
        # Try common product patterns
        for selector in [".sgf-dr-card", ".dotd-product", ".col-3", ".product-item"]:
            try:
                items = page.locator(selector)
                if items.count() > 0:
                    for i in range(min(items.count(), 10)):  # Limit to 10 for demo
                        try:
                            item = items.nth(i)
                            
                            # Basic title extraction
                            title = ""
                            if item.locator("h3").count() > 0:
                                title = item.locator("h3").first.text_content().strip()
                            elif item.locator(".title").count() > 0:
                                title = item.locator(".title").first.text_content().strip()
                            
                            # Basic price extraction
                            price = ""
                            if item.locator(".price").count() > 0:
                                price = item.locator(".price").first.text_content().strip()
                            elif item.locator(".price-new").count() > 0:
                                price = item.locator(".price-new").first.text_content().strip()
                            
                            # Basic URL extraction
                            url = ""
                            if item.locator("a").count() > 0:
                                url = item.locator("a").first.get_attribute("href")
                            
                            if title and price and url:
                                data.append({
                                    "title": title,
                                    "price": price,
                                    "url": url
                                })
                            
                        except Exception as e:
                            print(f"Error processing item {i}: {e}")
                            continue
                    break  # Stop after finding some data
                
            except Exception as e:
                print(f"Selector {selector} failed: {e}")
                continue
        
        browser.close()
        return data

@app.get("/data")
def get_data():
    return scrape_data()

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8011)
