# Auto-generated by Hermes AI Agent
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from playwright.sync_api import sync_playwright
import os

app = FastAPI()

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Health endpoint
@app.get("/health")
def health():
    return {"status": "ok"}

def scrape_data():
    data = []
    
    with sync_playwright() as p:
        browser = p.chromium.launch(args=["--no-sandbox", "--disable-dev-shm-usage"])
        context = browser.new_context(ignore_https_errors=True)
        page = context.new_page()
        
        # Navigate and wait for full load including JS
        page.goto("https://www.dr.com.tr/", wait_until="load", timeout=60000)
        
        # Scroll to trigger lazy loading
        for _ in range(5):
            page.evaluate("window.scrollTo(0, document.body ? document.body.scrollHeight : 0)")
            page.wait_for_timeout(2000)
        
        # Use multiple selector patterns to maximize data capture
        product_selectors = [
            ".product",
            ".item", 
            ".col-3",
            ".product-item",
            ".sgf-dr-card",
            ".dotd-product"
        ]
        
        # Try each selector pattern until we find matching products
        for selector in product_selectors:
            try:
                items = page.locator(selector).all()
                print(f"Found {len(items)} items with selector: {selector}")
                
                if items and len(items) > 0:
                    for item in items:
                        try:
                            # Extract title
                            title_element = item.locator(".title, .product-name, h3, span.title")
                            title = title_element.text_content().strip() if title_element.is_visible() else None
                            
                            # Extract price
                            price_element = item.locator(".price, .prices, .price-current, span.price")
                            price = price_element.text_content().strip() if price_element.is_visible() else None
                            
                            # Extract URL
                            url_element = item.locator("a")
                            url = url_element.get_attribute("href") if url_element.is_visible() else None
                            
                            if title and price and url:
                                data.append({
                                    "title": title,
                                    "price": price,
                                    "url": url
                                })
                        except Exception as e:
                            print(f"Error extracting from product: {e}")
                            continue
                    
                # Break early if we found a good set of products
                if len(data) > 10:  # Good threshold
                    break
                    
            except Exception as e:
                print(f"Selector failed: {selector} - {e}")
                continue
        
        browser.close()
        return data

@app.get("/data")
def get_data():
    return scrape_data()

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8011)
