"""
AutoAPI — SELF-HEALED by Hermes Agent
Target: http://localhost:8080 (Northbridge University Announcements)
Original Generated: 2025-03-05T10:00:00Z
Self-Healed At:     2025-03-05T10:47:33Z
AutoAPI — SELF-HEALED by Weaver Agent
============================================================
The target website's DOM structure changed. The agent has
re-analysed the structure and updated the CSS selectors
while perfectly preserving the original schema.
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from bs4 import BeautifulSoup
import httpx
import json
from datetime import datetime
from pathlib import Path

app = FastAPI(
    title="Weaver Auto-Scraper (Healed)",
    description="Auto-generated by Weaver Agent · v2 (Self-Healed)",
    version="1.0.1"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

TARGET_URL = "http://localhost:8080"
STATE_FILE = Path("state.json")


# ── Schema (UNCHANGED — backward compatible with v1) ────────────────────────
class Announcement(BaseModel):
    title: str
    category: str
    excerpt: str
    date: str
    department: str

class AnnouncementsResponse(BaseModel):
    source: str
    scraped_at: str
    schema_version: str = "1.0.0"
    count: int
    announcements: list[Announcement]

class HealthResponse(BaseModel):
    status: str
    last_successful_scrape: str | None
    announcement_count: int
    dom_fingerprint: str | None
    message: str


# ── Scraping logic — V2 selectors (post-heal DOM) ───────────────────────────
def scrape_v2(html: str) -> list[dict]:
    """
    Selectors updated after DOM change detected:
      card:       .ann-item          (was: .announcement-card)
      title:      .item-heading a    (was: .ann-title a)
      category:   .ann-category-badge
      excerpt:    .ann-excerpt
      date:       time.item-date     (was: time.ann-date)
      department: .item-dept         (was: .ann-department)
    """
    soup = BeautifulSoup(html, "html.parser")
    results = []

    for card in soup.select(".ann-item"):
        title_el    = card.select_one(".ann-heading a")
        excerpt_el  = card.select_one(".ann-excerpt")
        date_el     = card.select_one("time.ann-post-date")
        dept_el     = card.select_one(".ann-dept-label")
        badge_el    = card.select_one(".ann-category-badge")

        if not title_el:
            continue

        results.append({
            "title":      title_el.get_text(strip=True),
            "category":   badge_el.get_text(strip=True) if badge_el else "Unknown",
            "excerpt":    excerpt_el.get_text(strip=True) if excerpt_el else "",
            "date":       date_el.get("datetime", "") if date_el else "",
            "department": dept_el.get_text(strip=True) if dept_el else "",
        })

    return results


def compute_dom_fingerprint(html: str) -> str:
    soup = BeautifulSoup(html, "html.parser")
    cards = len(soup.select(".announcement-card"))
    items = len(soup.select(".ann-item"))
    return f"cards={cards}|items={items}"


def save_state(data: dict):
    STATE_FILE.write_text(json.dumps(data, indent=2))

def load_state() -> dict:
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text())
    return {}


# ── Routes (identical interface to v1) ──────────────────────────────────────
@app.get("/announcements", response_model=AnnouncementsResponse)
async def get_announcements():
    async with httpx.AsyncClient(timeout=10) as client:
        try:
            resp = await client.get(TARGET_URL)
            resp.raise_for_status()
        except Exception as e:
            raise HTTPException(status_code=502, detail=f"Cannot reach target: {e}")

    html = resp.text
    announcements = scrape_v2(html)

    if not announcements:
        raise HTTPException(
            status_code=503,
            detail="Scraper returned 0 results. Another DOM change detected. Triggering heal."
        )

    state = {
        "last_successful_scrape": datetime.utcnow().isoformat(),
        "announcement_count": len(announcements),
        "dom_fingerprint": compute_dom_fingerprint(html),
        "selector_version": "v2"
    }
    save_state(state)

    return AnnouncementsResponse(
        source=TARGET_URL,
        scraped_at=datetime.utcnow().isoformat(),
        count=len(announcements),
        announcements=announcements
    )


@app.get("/health", response_model=HealthResponse)
async def health_check():
    state = load_state()

    async with httpx.AsyncClient(timeout=10) as client:
        try:
            resp = await client.get(TARGET_URL)
            html = resp.text
        except Exception as e:
            return HealthResponse(
                status="broken",
                last_successful_scrape=state.get("last_successful_scrape"),
                announcement_count=0,
                dom_fingerprint=None,
                message=f"Target unreachable: {e}"
            )

    announcements = scrape_v2(html)
    fingerprint   = compute_dom_fingerprint(html)

    if not announcements:
        return HealthResponse(
            status="broken",
            last_successful_scrape=state.get("last_successful_scrape"),
            announcement_count=0,
            dom_fingerprint=fingerprint,
            message="Scraper returned 0 results — DOM structure likely changed again."
        )

    return HealthResponse(
        status="ok",
        last_successful_scrape=datetime.utcnow().isoformat(),
        announcement_count=len(announcements),
        dom_fingerprint=fingerprint,
        message="All systems nominal. (v2 selectors active)"
    )


@app.get("/state")
async def get_state():
    return load_state()
